# 빌드 단계
FROM node:20-alpine AS builder
WORKDIR /app
COPY package*.* ./
# docker-compose에서 build directive아래 args directive의 값이 들어온다.
ARG NODE_ENV   
ARG PORT
# NODE_ENV의 값은 루트디렉토리의 nodeenv.txt에 저장한다. '/'이 없으면 /app디렉토리에 저장되는데 아래의 'COPY . .'에 의해 host 디렉토리의 내용으로 지워져서 nodeenv.txt파일이 삭제된다.
RUN echo $NODE_ENV > /nodeenv.txt   
RUN npm ci
COPY . .
CMD ["node", "index.js"]

# # 실행 단계
# FROM node:20-alpine
# WORKDIR /app
# COPY --from=builder /app/dist ./dist
# CMD ["node", "dist/index.js"]